<?php
declare(strict_types=1);
$admin_page_title = 'Drivers & Verification';
require_once __DIR__ . '/components/admin_header.php';
$data = admin_page_data($conn, 'drivers', ['id' => $_GET['id'] ?? 0]);
$selected = $data['selected'];
?>
<main class="admin-main" id="admin-main" tabindex="-1">
<header class="admin-page-heading"><div><p class="admin-eyebrow">DELIVERY PARTNER GOVERNANCE</p><h1>Drivers &amp; Verification</h1><p>Review personal, operating-area, and vehicle details before activating a Driver account.</p></div></header>
<nav class="admin-tabs" aria-label="Driver sections"><a class="is-active" href="admin_drivers.php">Pending Applications</a><a href="admin_drivers.php?tab=active">Active Drivers</a><a href="admin_drivers.php?tab=review">Needs Review</a><a href="admin_drivers.php?tab=suspended">Suspended</a></nav>
<section class="admin-kpi-grid">
<article class="admin-kpi-card"><div class="admin-kpi-card__label">Pending Applications</div><strong><?= admin_escape($data['summary']['pending'] ?? 0) ?></strong><small>Awaiting Admin decision</small></article>
<article class="admin-kpi-card"><div class="admin-kpi-card__label">Active Drivers</div><strong><?= admin_escape(count($data['drivers'])) ?></strong><small>Approved delivery partners</small></article>
<article class="admin-kpi-card"><div class="admin-kpi-card__label">Needs Review</div><strong><?= admin_escape($data['summary']['needs_review'] ?? 0) ?></strong><small>Higher-risk applications</small></article>
<article class="admin-kpi-card admin-kpi-card--dark"><div class="admin-kpi-card__label">Average Queue Age</div><strong><?= admin_escape(round((float) ($data['summary']['average_age_hours'] ?? 0))) ?>h</strong><small>From submission</small></article>
</section>
<div class="admin-approval-layout">
<section class="admin-card admin-card--flush"><header class="admin-card__header admin-card__header--padded"><div><span class="admin-eyebrow">VERIFICATION</span><h2>Application Queue</h2></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Applicant</th><th>Vehicle</th><th>Area</th><th>Risk</th><th>Submitted</th><th></th></tr></thead><tbody><?php foreach ($data['applications'] as $app): ?><tr><td><strong><?= admin_escape($app['full_name']) ?></strong><small class="admin-cell-note"><?= admin_escape($app['reference_code']) ?></small></td><td><?= admin_escape($app['vehicle_type']) ?></td><td><?= admin_escape($app['service_area']) ?></td><td><span class="admin-risk admin-risk--<?= admin_escape($app['risk_level']) ?>"><?= admin_escape($app['risk_level']) ?></span></td><td><?= admin_escape(date('M j, H:i', strtotime((string) $app['submitted_at']))) ?></td><td><a class="admin-row-action" href="admin_drivers.php?id=<?= admin_escape($app['id']) ?>" aria-label="Review <?= admin_escape($app['full_name']) ?>"><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside class="admin-detail-panel admin-approval-panel">
<?php if ($selected): ?>
<header><span class="admin-eyebrow">APPLICATION <?= admin_escape($selected['reference_code']) ?></span><h2><?= admin_escape($selected['full_name']) ?></h2><p><?= admin_escape($selected['email']) ?> · <?= admin_escape($selected['city']) ?></p></header>
<dl class="admin-detail-list">
<div><dt>Full name</dt><dd><?= admin_escape($selected['full_name']) ?></dd></div><div><dt>Username</dt><dd><?= admin_escape($selected['username']) ?></dd></div>
<div><dt>Email</dt><dd><?= admin_escape($selected['email']) ?></dd></div><div><dt>Phone</dt><dd><?= admin_escape($selected['phone']) ?></dd></div>
<div><dt>City</dt><dd><?= admin_escape($selected['city']) ?></dd></div><div><dt>Operating area</dt><dd><?= admin_escape($selected['service_area']) ?></dd></div>
<div><dt>Vehicle type</dt><dd><?= admin_escape($selected['vehicle_type']) ?></dd></div><div><dt>Vehicle model</dt><dd><?= admin_escape($selected['vehicle_model']) ?></dd></div>
<div><dt>License plate</dt><dd><?= admin_escape($selected['license_plate']) ?></dd></div><div><dt>Vehicle color</dt><dd><?= admin_escape($selected['vehicle_color'] ?: 'Not provided') ?></dd></div>
<div><dt>Risk</dt><dd><?= admin_escape(ucfirst((string) $selected['risk_level'])) ?></dd></div><div><dt>Status</dt><dd><?= admin_escape(ucfirst((string) $selected['status'])) ?></dd></div>
</dl>
<label class="admin-reason-box"><span>Reviewer note</span><textarea rows="3" data-admin-reviewer-note placeholder="Required when rejecting an application"><?= admin_escape($selected['reviewer_note'] ?? '') ?></textarea></label>
<div class="admin-detail-actions"><button class="admin-button admin-button--danger" type="button" data-admin-partner-action="reject_driver" data-application-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Reject Application</button><button class="admin-button admin-button--primary" type="button" data-admin-partner-action="approve_driver" data-application-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Approve Driver</button></div>
<p class="admin-integrity-note"><i class="fa-solid fa-shield" aria-hidden="true"></i>Approval creates one active Driver account with offline availability.</p>
<?php endif; ?>
</aside></div>
<section class="admin-card admin-card--flush"><header class="admin-card__header admin-card__header--padded"><div><span class="admin-eyebrow">DELIVERY NETWORK</span><h2>Active Drivers</h2></div></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Driver</th><th>Vehicle</th><th>Area</th><th>Eligibility</th><th>Availability</th><th>Acceptance</th><th>Completion</th></tr></thead><tbody><?php foreach ($data['drivers'] as $driver): ?><tr><td><strong><?= admin_escape($driver['full_name']) ?></strong><small class="admin-cell-note"><?= admin_escape($driver['email']) ?></small></td><td><?= admin_escape($driver['vehicle_type']) ?> <?= admin_escape($driver['vehicle_model']) ?></td><td><?= admin_escape($driver['service_area']) ?></td><td><span class="admin-status admin-status--<?= admin_escape($driver['eligibility_status']) ?>"><i aria-hidden="true"></i><?= admin_escape(ucfirst((string) $driver['eligibility_status'])) ?></span></td><td><?= admin_escape(ucfirst((string) $driver['availability_status'])) ?></td><td><?= admin_escape($driver['acceptance_rate']) ?>%</td><td><?= admin_escape($driver['completion_rate']) ?>%</td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="admin-card admin-section-block" aria-labelledby="driver-gps-title"><header class="admin-card__header"><div><span class="admin-eyebrow">LOCATION VISIBILITY</span><h2 id="driver-gps-title">Driver GPS addresses</h2></div><span class="admin-muted-copy">Read-only</span></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Driver</th><th>GPS address</th><th>Coordinates</th><th>Method</th><th>Updated</th></tr></thead><tbody><?php foreach ($data['drivers'] as $driver): ?><tr><td><?= admin_escape($driver['full_name']) ?></td><td><?= admin_escape($driver['location_address'] ?: 'Not set') ?></td><td><?= $driver['latitude'] !== null && $driver['longitude'] !== null ? admin_escape($driver['latitude'] . ', ' . $driver['longitude']) : '-' ?></td><td><?= admin_escape(($driver['location_method'] ?? 'manual') === 'gps' ? 'GPS' : 'Manual') ?></td><td><?= admin_escape($driver['location_updated_at'] ?: 'Not updated') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</main>
<?php require_once __DIR__ . '/components/admin_footer.php'; ?>
