<?php
declare(strict_types=1);
$admin_page_title = 'Accounts & Access';
require_once __DIR__ . '/components/admin_header.php';
$accountsData = admin_page_data($conn, 'accounts', ['q' => $_GET['q'] ?? '', 'role' => $_GET['role'] ?? '', 'status' => $_GET['status'] ?? '', 'id' => $_GET['id'] ?? 0]);
$selected = $accountsData['selected'];
?>
<main class="admin-main" id="admin-main" tabindex="-1">
    <header class="admin-page-heading"><div><p class="admin-eyebrow">IDENTITY &amp; SECURITY</p><h1>Accounts &amp; Access</h1><p>Monitor every role, session and status change with controlled Admin interventions.</p></div><div class="admin-page-heading__actions"><button class="admin-button admin-button--ghost" type="button" data-admin-export-table><i class="fa-solid fa-download" aria-hidden="true"></i> Export accounts</button></div></header>
    <section class="admin-summary-strip" aria-label="Account summary"><?php foreach ([['All Accounts','all','fa-users'],['Active','active','fa-circle-check'],['Suspended','suspended','fa-pause'],['Blocked','blocked','fa-ban'],['Pending','pending','fa-clock']] as [$label,$key,$icon]): ?><a href="admin_accounts.php<?= $key === 'all' ? '' : '?status=' . admin_escape($key) ?>"><span><i class="fa-solid <?= admin_escape($icon) ?>" aria-hidden="true"></i><?= admin_escape($label) ?></span><strong><?= admin_escape($accountsData['summary'][$key] ?? 0) ?></strong></a><?php endforeach; ?></section>
    <form class="admin-filter-bar" method="get" data-admin-filter><label class="admin-filter-search"><span class="sr-only">Search accounts</span><input type="search" name="q" value="<?= admin_escape($_GET['q'] ?? '') ?>" placeholder="Search name, username or email"></label><label><span>Role</span><select name="role"><option value="">All roles</option><?php foreach (['customer','restaurant','driver','admin'] as $role): ?><option value="<?= $role ?>" <?= ($_GET['role'] ?? '') === $role ? 'selected' : '' ?>><?= admin_escape(ucfirst($role)) ?></option><?php endforeach; ?></select></label><label><span>Status</span><select name="status"><option value="">All statuses</option><?php foreach (['active','suspended','blocked','pending'] as $status): ?><option value="<?= $status ?>" <?= ($_GET['status'] ?? '') === $status ? 'selected' : '' ?>><?= admin_escape(ucfirst($status)) ?></option><?php endforeach; ?></select></label><label><span>Created date</span><input type="date" name="created"></label><button class="admin-button admin-button--primary" type="submit">Apply</button></form>
    <div class="admin-master-detail">
        <section class="admin-card admin-card--flush"><header class="admin-card__header admin-card__header--padded"><div><span class="admin-eyebrow">DIRECTORY</span><h2>All Accounts</h2></div><span class="admin-result-count"><?= admin_escape(count($accountsData['accounts'])) ?> results</span></header><div class="admin-table-wrap"><table class="admin-table" data-admin-table><thead><tr><th>Account</th><th>Role</th><th>Status</th><th>Last login</th><th>Created</th><th>Version</th><th></th></tr></thead><tbody><?php foreach ($accountsData['accounts'] as $account): ?><tr data-search="<?= admin_escape(strtolower($account['full_name'].' '.$account['username'].' '.$account['email'])) ?>" data-status="<?= admin_escape($account['status']) ?>"><td><div class="admin-person"><span class="admin-avatar admin-avatar--soft"><?= admin_escape(strtoupper(substr((string) $account['full_name'],0,1))) ?></span><span><strong><?= admin_escape($account['full_name']) ?></strong><small>@<?= admin_escape($account['username']) ?></small></span></div></td><td><span class="admin-role-label"><?= admin_escape(ucfirst((string) $account['role'])) ?></span></td><td><span class="admin-status admin-status--<?= admin_escape($account['status']) ?>"><i aria-hidden="true"></i><?= admin_escape(ucfirst((string) $account['status'])) ?></span></td><td><?= admin_escape($account['last_login_at'] ? date('M j, H:i',strtotime((string)$account['last_login_at'])) : 'Never') ?></td><td><?= admin_escape(date('M j, Y',strtotime((string)$account['created_at']))) ?></td><td>v<?= admin_escape($account['version']) ?></td><td><a class="admin-row-action" href="admin_accounts.php?id=<?= admin_escape($account['id']) ?>" aria-label="View <?= admin_escape($account['full_name']) ?>"><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a></td></tr><?php endforeach; ?></tbody></table></div></section>
        <aside class="admin-detail-panel" aria-label="Selected account details">
            <?php if ($selected): ?><header class="admin-detail-panel__profile"><span class="admin-avatar"><?= admin_escape(strtoupper(substr((string)$selected['full_name'],0,1))) ?></span><div><span class="admin-eyebrow">ACCOUNT #<?= admin_escape($selected['id']) ?></span><h2><?= admin_escape($selected['full_name']) ?></h2><p><?= admin_escape($selected['email']) ?></p></div><span class="admin-status admin-status--<?= admin_escape($selected['status']) ?>"><i aria-hidden="true"></i><?= admin_escape(ucfirst((string)$selected['status'])) ?></span></header>
            <dl class="admin-detail-list"><div><dt>Role</dt><dd><?= admin_escape(ucfirst((string)$selected['role'])) ?></dd></div><div><dt>Username</dt><dd>@<?= admin_escape($selected['username']) ?></dd></div><div><dt>Last login</dt><dd><?= admin_escape($selected['last_login_at'] ?: 'Never') ?></dd></div><div><dt>Session version</dt><dd><?= admin_escape($selected['session_version']) ?></dd></div></dl>
            <section><h3>Security History</h3><?php if (!$accountsData['status_history']): ?><p class="admin-muted-copy">No manual status changes recorded.</p><?php endif; ?><?php foreach ($accountsData['status_history'] as $history): ?><article class="admin-mini-event"><i class="fa-solid fa-shield" aria-hidden="true"></i><div><strong><?= admin_escape(ucfirst((string)$history['previous_status'])) ?> → <?= admin_escape(ucfirst((string)$history['next_status'])) ?></strong><p><?= admin_escape($history['reason']) ?></p><small><?= admin_escape($history['actor_name']) ?> · <?= admin_escape(date('M j, H:i',strtotime((string)$history['created_at']))) ?></small></div></article><?php endforeach; ?></section>
            <section><h3>Active Sessions</h3><p class="admin-muted-copy"><?= admin_escape(count(array_filter($accountsData['sessions'], static fn(array $s): bool => $s['revoked_at'] === null))) ?> active session records.</p></section>
            <label class="admin-reason-box"><span>Intervention reason</span><textarea name="reason" rows="2" data-admin-account-reason placeholder="Required for security actions"></textarea></label>
            <div class="admin-detail-actions"><?php if ($selected['role'] === 'admin'): ?><p class="admin-protected-note"><i class="fa-solid fa-lock" aria-hidden="true"></i>The only Admin account is protected.</p><?php else: ?><?php if ($selected['status'] === 'active'): ?><button class="admin-button admin-button--ghost" type="button" data-admin-confirm-action="suspend_account" data-user-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Suspend Account</button><?php else: ?><button class="admin-button admin-button--ghost" type="button" data-admin-confirm-action="reactivate_account" data-user-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Reactivate Account</button><?php endif; ?><button class="admin-button admin-button--ghost" type="button" data-admin-confirm-action="revoke_sessions" data-user-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Revoke Sessions</button><button class="admin-button admin-button--ghost" type="button" data-admin-confirm-action="reset_password" data-user-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Reset Password</button><button class="admin-button admin-button--danger" type="button" data-admin-confirm-action="block_account" data-user-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Block Account</button><?php endif; ?></div>
            <?php endif; ?>
        </aside>
    </div>
</main>
<?php require_once __DIR__ . '/components/admin_footer.php'; ?>
