<?php
declare(strict_types=1);
$admin_page_title = 'Customers';
require_once __DIR__ . '/components/admin_header.php';
$customersData = admin_page_data($conn, 'customers', ['q' => $_GET['q'] ?? '', 'id' => $_GET['id'] ?? 0]);
$selected = $customersData['selected'];
function admin_mask_email(string $email): string { $parts = explode('@',$email,2); return substr($parts[0],0,2).'•••@'.($parts[1] ?? 'private'); }
?>
<main class="admin-main" id="admin-main" tabindex="-1">
    <header class="admin-page-heading"><div><p class="admin-eyebrow">CUSTOMER OPERATIONS</p><h1>Customers</h1><p>Review Customer activity, wallet history, orders and support context without editing derived balances.</p></div></header>
    <section class="admin-kpi-grid"><article class="admin-kpi-card"><span class="admin-kpi-card__icon"><i class="fa-solid fa-users" aria-hidden="true"></i></span><div class="admin-kpi-card__label">Total Customers</div><strong><?= admin_escape((int)($customersData['summary']['total_customers'] ?? 0)) ?></strong><small>Registered identities</small></article><article class="admin-kpi-card"><span class="admin-kpi-card__icon admin-kpi-card__icon--blue"><i class="fa-solid fa-basket-shopping" aria-hidden="true"></i></span><div class="admin-kpi-card__label">Average Order Value</div><strong>$<?= admin_escape(number_format((float)($customersData['summary']['average_order_value'] ?? 0),2)) ?></strong><small>Across Customer orders</small></article><article class="admin-kpi-card"><span class="admin-kpi-card__icon admin-kpi-card__icon--coral"><i class="fa-solid fa-life-ring" aria-hidden="true"></i></span><div class="admin-kpi-card__label">Open Cases</div><strong><?= admin_escape((int)($customersData['summary']['open_cases'] ?? 0)) ?></strong><small>Awaiting resolution</small></article><article class="admin-kpi-card admin-kpi-card--dark"><span class="admin-kpi-card__icon"><i class="fa-solid fa-wallet" aria-hidden="true"></i></span><div class="admin-kpi-card__label">Wallet Balance</div><strong>$<?= admin_escape(number_format((float)($customersData['summary']['wallet_balance'] ?? 0),2)) ?></strong><small>Ledger-derived total</small></article></section>
    <form class="admin-filter-bar" method="get" data-admin-filter><label class="admin-filter-search"><span class="sr-only">Search Customers</span><input type="search" name="q" value="<?= admin_escape($_GET['q'] ?? '') ?>" placeholder="Search Customer name or email"></label><button class="admin-button admin-button--primary" type="submit">Search</button></form>
    <div class="admin-master-detail admin-master-detail--customer"><section class="admin-card admin-card--flush"><header class="admin-card__header admin-card__header--padded"><div><span class="admin-eyebrow">CUSTOMER DIRECTORY</span><h2>Customer Accounts</h2></div><span class="admin-result-count"><?= admin_escape(count($customersData['customers'])) ?> results</span></header><div class="admin-table-wrap"><table class="admin-table" data-admin-table><thead><tr><th>Customer</th><th>Orders</th><th>Lifetime value</th><th>Wallet</th><th>Cases</th><th>Status</th><th></th></tr></thead><tbody><?php foreach ($customersData['customers'] as $customer): ?><tr><td><div class="admin-person"><span class="admin-avatar admin-avatar--soft"><?= admin_escape(strtoupper(substr((string)$customer['full_name'],0,1))) ?></span><span><strong><?= admin_escape($customer['full_name']) ?></strong><small><?= admin_escape(admin_mask_email((string)$customer['email'])) ?> · Masked for privacy</small></span></div></td><td><?= admin_escape($customer['order_count']) ?></td><td>$<?= admin_escape(number_format((float)$customer['lifetime_value'],2)) ?></td><td>$<?= admin_escape(number_format((float)$customer['wallet_balance'],2)) ?></td><td><?= admin_escape($customer['open_cases']) ?></td><td><span class="admin-status admin-status--<?= admin_escape($customer['status']) ?>"><i aria-hidden="true"></i><?= admin_escape(ucfirst((string)$customer['status'])) ?></span></td><td><a class="admin-row-action" href="admin_customers.php?id=<?= admin_escape($customer['id']) ?>"><i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a></td></tr><?php endforeach; ?></tbody></table></div></section>
        <aside class="admin-detail-panel admin-customer-panel"><?php if ($selected): ?><header class="admin-detail-panel__profile"><span class="admin-avatar"><?= admin_escape(strtoupper(substr((string)$selected['full_name'],0,1))) ?></span><div><span class="admin-eyebrow">Customer Profile</span><h2><?= admin_escape($selected['full_name']) ?></h2><p><?= admin_escape(admin_mask_email((string)$selected['email'])) ?> · Masked for privacy</p></div></header><nav class="admin-mini-tabs" aria-label="Customer details"><span>Order History</span><span>Wallet Ledger</span><span>Support Cases</span><span>Security</span></nav><section><h3>Order History</h3><?php foreach ($customersData['orders'] as $order): ?><a class="admin-mini-record" href="admin_orders.php?id=<?= admin_escape($order['id']) ?>"><span><strong><?= admin_escape($order['reference_code']) ?></strong><small><?= admin_escape(date('M j, Y',strtotime((string)$order['placed_at']))) ?></small></span><span class="admin-status admin-status--<?= admin_escape($order['status']) ?>"><i aria-hidden="true"></i><?= admin_escape(ucwords(str_replace('_',' ',(string)$order['status']))) ?></span><b>$<?= admin_escape(number_format((float)$order['total'],2)) ?></b></a><?php endforeach; ?></section><section><h3>Wallet Ledger</h3><?php if (!$customersData['wallet']): ?><p class="admin-muted-copy">No wallet transactions. Balance cannot be edited directly.</p><?php endif; ?><?php foreach ($customersData['wallet'] as $entry): ?><div class="admin-mini-record"><span><strong><?= admin_escape($entry['description']) ?></strong><small><?= admin_escape(date('M j, H:i',strtotime((string)$entry['created_at']))) ?></small></span><b><?= (float)$entry['amount'] >= 0 ? '+' : '' ?>$<?= admin_escape(number_format((float)$entry['amount'],2)) ?></b></div><?php endforeach; ?></section><div class="admin-detail-actions"><button class="admin-button admin-button--danger" type="button" data-admin-confirm-action="suspend_account" data-user-id="<?= admin_escape($selected['id']) ?>" data-version="<?= admin_escape($selected['version']) ?>">Suspend Account</button><a class="admin-button admin-button--ghost" href="admin_accounts.php?id=<?= admin_escape($selected['id']) ?>">Open Security</a></div><?php endif; ?></aside>
    </div>
<section class="admin-card admin-section-block" aria-labelledby="customer-gps-title"><header class="admin-card__header"><div><span class="admin-eyebrow">LOCATION VISIBILITY</span><h2 id="customer-gps-title">Customer GPS addresses</h2></div><span class="admin-muted-copy">Read-only</span></header><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Customer</th><th>GPS address</th><th>Coordinates</th><th>Method</th></tr></thead><tbody><?php foreach ($customersData['customers'] as $customer): ?><tr><td><?= admin_escape($customer['full_name']) ?></td><td><?= admin_escape($customer['location_address'] ?: 'Not set') ?></td><td><?= $customer['latitude'] !== null && $customer['longitude'] !== null ? admin_escape($customer['latitude'] . ', ' . $customer['longitude']) : '—' ?></td><td><?= admin_escape(($customer['location_method'] ?? 'manual') === 'gps' ? 'GPS' : 'Manual') ?></td></tr><?php endforeach; ?></tbody></table></div></section>
</main>
<?php require_once __DIR__ . '/components/admin_footer.php'; ?>
