<?php
declare(strict_types=1);

require_once __DIR__ . '/../idempotency.php';
require_once __DIR__ . '/notification_service.php';
require_once __DIR__ . '/audit_service.php';

function admin_order_result(bool $ok, int $status, string $message, array $data = []): array { $result = ['ok' => $ok, 'status' => $status, 'message' => $message, 'referenceId' => 'ADM-ORD-' . strtoupper(bin2hex(random_bytes(5)))]; if ($data !== []) $result['data'] = $data; return $result; }
function admin_order_actor(mysqli $conn, int $actorId): bool { $row = $conn->prepare("SELECT id FROM users WHERE id=? AND role='admin' AND status='active' LIMIT 1"); $row->bind_param('i', $actorId); $row->execute(); $ok = $row->get_result()->fetch_assoc() !== null; $row->close(); return $ok; }
function admin_order_reason(mixed $reason): string { $value = trim((string) $reason); if ($value === '' || mb_strlen($value) > 500) throw new InvalidArgumentException('A bounded Admin reason is required.'); return $value; }
function admin_order_notify(mysqli $conn, array $recipients, string $event, string $message, int $orderId): void { foreach (array_unique(array_filter(array_map('intval', $recipients))) as $recipient) notification_queue($conn, $recipient, $event, 'Order operations update', $message, 'order', $orderId); }

function admin_cancel_order(mysqli $conn, int $actorId, int $orderId, string $reason, int $expectedVersion, string $idempotencyKey): array
{
    if (!admin_order_actor($conn, $actorId)) return admin_order_result(false, 403, 'Admin authorization is required.');
    $reason = admin_order_reason($reason); if ($orderId <= 0 || $expectedVersion <= 0 || trim($idempotencyKey) === '') return admin_order_result(false, 422, 'Order, version, reason and idempotency key are required.');
    $hash = savora_idempotency_hash('cancel_order', ['orderId' => $orderId, 'version' => $expectedVersion, 'reason' => $reason]); $conn->begin_transaction();
    try {
        $stored = savora_idempotency_find($conn, $actorId, $idempotencyKey, 'cancel_order', $hash); if ($stored !== null) { $conn->commit(); return $stored; }
        $lock = $conn->prepare('SELECT o.*,r.owner_user_id FROM orders o JOIN restaurants r ON r.id=o.restaurant_id WHERE o.id=? FOR UPDATE'); $lock->bind_param('i', $orderId); $lock->execute(); $before = $lock->get_result()->fetch_assoc(); $lock->close();
        if (!$before) throw new RuntimeException('Order not found.'); if ((int) $before['version'] !== $expectedVersion) throw new RuntimeException('Order has a stale version.'); if (in_array((string) $before['status'], ['delivered','completed','cancelled','refunded'], true)) throw new RuntimeException('Final orders cannot be cancelled.');
        $offers = $conn->prepare("UPDATE delivery_offers do JOIN delivery_dispatches dd ON dd.id=do.dispatch_id SET do.status='expired',do.expired_at=NOW(),do.responded_at=NOW(),do.response_code='order_cancelled',do.active_dispatch_key=NULL,do.active_driver_key=NULL WHERE dd.order_id=? AND do.status='sent'"); $offers->bind_param('i', $orderId); $offers->execute(); $offers->close();
        $dispatch = $conn->prepare("UPDATE delivery_dispatches SET status='cancelled',assigned_driver_user_id=NULL,version=version+1 WHERE order_id=? AND status NOT IN ('cancelled','completed')"); $dispatch->bind_param('i', $orderId); $dispatch->execute(); $dispatch->close();
        $drivers = []; $deliveries = $conn->prepare("SELECT id,driver_user_id,status FROM deliveries WHERE order_id=? AND status NOT IN ('delivered','cancelled','superseded') FOR UPDATE"); $deliveries->bind_param('i', $orderId); $deliveries->execute(); $deliveryRows = $deliveries->get_result()->fetch_all(MYSQLI_ASSOC); $deliveries->close();
        foreach ($deliveryRows as $delivery) { $drivers[] = (int) $delivery['driver_user_id']; $update = $conn->prepare("UPDATE deliveries SET status='cancelled',version=version+1,failed_at=NULL,failure_reason=? WHERE id=?"); $update->bind_param('si', $reason, $delivery['id']); $update->execute(); $update->close(); }
        $payment = $conn->prepare('SELECT id,method,status,amount FROM payments WHERE order_id=? FOR UPDATE'); $payment->bind_param('i', $orderId); $payment->execute(); $paymentRow = $payment->get_result()->fetch_assoc(); $payment->close();
        if ($paymentRow && (string) $paymentRow['status'] === 'paid') {
            if ((string) $paymentRow['method'] === 'card') { $change = $conn->prepare("UPDATE payments SET status='refund_pending',version=version+1 WHERE id=?"); $change->bind_param('i', $paymentRow['id']); $change->execute(); $change->close(); }
            elseif ((string) $paymentRow['method'] === 'wallet') { $amount = (float) $paymentRow['amount']; $wallet = $conn->prepare('UPDATE customer_profiles SET wallet_balance=wallet_balance+? WHERE user_id=?'); $wallet->bind_param('di', $amount, $before['customer_user_id']); $wallet->execute(); $wallet->close(); $credit = $conn->prepare("INSERT INTO wallet_transactions(customer_user_id,order_id,type,amount,description) VALUES(?,?,'credit',?,'Cancellation compensation')"); $credit->bind_param('iid', $before['customer_user_id'], $orderId, $amount); $credit->execute(); $credit->close(); $change = $conn->prepare("UPDATE payments SET status='refunded',version=version+1 WHERE id=?"); $change->bind_param('i', $paymentRow['id']); $change->execute(); $change->close(); }
            else { $change = $conn->prepare("UPDATE payments SET status='cancelled',version=version+1 WHERE id=?"); $change->bind_param('i', $paymentRow['id']); $change->execute(); $change->close(); }
        }
        $update = $conn->prepare("UPDATE orders SET status='cancelled',version=version+1 WHERE id=? AND version=?"); $update->bind_param('ii', $orderId, $expectedVersion); $update->execute(); if ($update->affected_rows !== 1) throw new RuntimeException('Order changed before cancellation completed.'); $update->close();
        $history = $conn->prepare("INSERT INTO order_status_history(order_id,status,actor_role,actor_user_id,reason) VALUES(?,'cancelled','admin',?,?)"); $history->bind_param('iis', $orderId, $actorId, $reason); $history->execute(); $history->close();
        admin_order_notify($conn, array_merge([(int) $before['customer_user_id'], (int) $before['owner_user_id']], $drivers), 'order_cancelled', 'Order ' . (string) $before['reference_code'] . ' was cancelled by Operations.', $orderId);
        $after = ['status' => 'cancelled', 'version' => $expectedVersion + 1, 'paymentStatus' => $paymentRow['method'] ?? null]; $reference = 'ADM-ORD-' . strtoupper(bin2hex(random_bytes(5))); audit_append($conn, $actorId, 'cancel_order', 'order', $orderId, ['status' => $before['status'], 'version' => $expectedVersion], $after, $reason, $reference); $response = ['ok' => true, 'status' => 200, 'message' => 'Order cancelled atomically.', 'referenceId' => $reference, 'data' => $after]; savora_idempotency_store($conn, $actorId, $idempotencyKey, 'cancel_order', $hash, $response); $conn->commit(); return $response;
    } catch (Throwable $exception) { $conn->rollback(); return admin_order_result(false, $exception instanceof InvalidArgumentException ? 422 : 409, $exception->getMessage()); }
}

function admin_reassign_driver(mysqli $conn, int $actorId, int $orderId, int $driverId, string $reason, int $expectedVersion, string $idempotencyKey): array
{
    if (!admin_order_actor($conn, $actorId)) return admin_order_result(false, 403, 'Admin authorization is required.');
    $reason = admin_order_reason($reason); if ($orderId <= 0 || $driverId <= 0 || $expectedVersion <= 0 || trim($idempotencyKey) === '') return admin_order_result(false, 422, 'Order, Driver, version, reason and idempotency key are required.');
    $payload = ['orderId' => $orderId, 'driverId' => $driverId, 'version' => $expectedVersion, 'reason' => $reason]; $hash = savora_idempotency_hash('reassign_driver', $payload); $conn->begin_transaction();
    try {
        $stored = savora_idempotency_find($conn, $actorId, $idempotencyKey, 'reassign_driver', $hash); if ($stored !== null) { $conn->commit(); return $stored; }
        $lock = $conn->prepare('SELECT o.*,r.owner_user_id FROM orders o JOIN restaurants r ON r.id=o.restaurant_id WHERE o.id=? FOR UPDATE'); $lock->bind_param('i', $orderId); $lock->execute(); $order = $lock->get_result()->fetch_assoc(); $lock->close(); if (!$order) throw new RuntimeException('Order not found.'); if ((int) $order['version'] !== $expectedVersion) throw new RuntimeException('Order has a stale version.'); if (!in_array((string) $order['status'], ['ready_for_pickup','assigned'], true)) throw new RuntimeException('Driver assignment is only allowed for an active dispatch.');
        $driver = $conn->prepare("SELECT u.id,dp.availability_status FROM users u JOIN driver_profiles dp ON dp.user_id=u.id WHERE u.id=? AND u.role='driver' AND u.status='active' AND dp.eligibility_status='eligible' FOR UPDATE"); $driver->bind_param('i', $driverId); $driver->execute(); $driverRow = $driver->get_result()->fetch_assoc(); $driver->close(); if (!$driverRow) throw new RuntimeException('Selected Driver is not eligible.');
        $busy = $conn->prepare("SELECT id FROM deliveries WHERE driver_user_id=? AND status IN ('assigned','arrived','picked_up') AND superseded_at IS NULL LIMIT 1 FOR UPDATE"); $busy->bind_param('i', $driverId); $busy->execute(); if ($busy->get_result()->fetch_assoc()) throw new RuntimeException('Selected Driver already has an active delivery.'); $busy->close();
        $old = $conn->prepare("SELECT id,driver_user_id,status FROM deliveries WHERE order_id=? AND superseded_at IS NULL ORDER BY id DESC LIMIT 1 FOR UPDATE"); $old->bind_param('i', $orderId); $old->execute(); $oldRow = $old->get_result()->fetch_assoc(); $old->close(); $oldDriverId = (int) ($oldRow['driver_user_id'] ?? 0);
        if ($oldRow && (int) $oldRow['driver_user_id'] === $driverId) throw new RuntimeException('Order is already assigned to this Driver.');
        if ($oldRow) { $close = $conn->prepare("UPDATE deliveries SET status='superseded',superseded_at=NOW(),version=version+1 WHERE id=?"); $close->bind_param('i', $oldRow['id']); $close->execute(); $close->close(); }
        $earning = (float) $order['delivery_fee']; $insert = $conn->prepare("INSERT INTO deliveries(order_id,driver_user_id,status,earning,accepted_at,version) VALUES(?,?, 'assigned',?,NOW(),1)"); $insert->bind_param('iid', $orderId, $driverId, $earning); $insert->execute(); $newDeliveryId = (int) $insert->insert_id; $insert->close(); if ($oldRow) { $link = $conn->prepare('UPDATE deliveries SET superseded_by_delivery_id=? WHERE id=?'); $link->bind_param('ii', $newDeliveryId, $oldRow['id']); $link->execute(); $link->close(); }
        $dispatch = $conn->prepare("INSERT INTO delivery_dispatches(order_id,status,assigned_driver_user_id,attempt_count) VALUES(?,'assigned',?,1) ON DUPLICATE KEY UPDATE status='assigned',assigned_driver_user_id=VALUES(assigned_driver_user_id),attempt_count=attempt_count+1,version=version+1"); $dispatch->bind_param('ii', $orderId, $driverId); $dispatch->execute(); $dispatch->close();
        $update = $conn->prepare("UPDATE orders SET status='assigned',version=version+1 WHERE id=? AND version=?"); $update->bind_param('ii', $orderId, $expectedVersion); $update->execute(); if ($update->affected_rows !== 1) throw new RuntimeException('Order changed before reassignment completed.'); $update->close(); $history = $conn->prepare("INSERT INTO order_status_history(order_id,status,actor_role,actor_user_id,reason) VALUES(?,'assigned','admin',?,?)"); $history->bind_param('iis', $orderId, $actorId, $reason); $history->execute(); $history->close();
        if ($oldDriverId > 0) { $oldAvailability = $conn->prepare("UPDATE driver_profiles SET availability_status='online',version=version+1 WHERE user_id=? AND availability_status='busy'"); $oldAvailability->bind_param('i', $oldDriverId); $oldAvailability->execute(); $oldAvailability->close(); }
        $newAvailability = $conn->prepare("UPDATE driver_profiles SET availability_status='busy',version=version+1 WHERE user_id=?"); $newAvailability->bind_param('i', $driverId); $newAvailability->execute(); $newAvailability->close();
        admin_order_notify($conn, array_filter([(int) $order['customer_user_id'], (int) $order['owner_user_id'], $oldDriverId, $driverId]), 'delivery_reassigned', 'Order ' . (string) $order['reference_code'] . ' was reassigned by Operations.', $orderId); $after = ['deliveryId' => $newDeliveryId, 'driverUserId' => $driverId, 'status' => 'assigned', 'version' => $expectedVersion + 1]; $reference = 'ADM-ORD-' . strtoupper(bin2hex(random_bytes(5))); audit_append($conn, $actorId, 'reassign_driver', 'order', $orderId, ['driverUserId' => $oldDriverId], $after, $reason, $reference); $response = ['ok' => true, 'status' => 200, 'message' => 'Driver reassigned atomically.', 'referenceId' => $reference, 'data' => $after]; savora_idempotency_store($conn, $actorId, $idempotencyKey, 'reassign_driver', $hash, $response); $conn->commit(); return $response;
    } catch (Throwable $exception) { $conn->rollback(); return admin_order_result(false, $exception instanceof InvalidArgumentException ? 422 : 409, $exception->getMessage()); }
}
