<?php
declare(strict_types=1);
if (getenv('SAVORA_ENV') !== 'test' || getenv('SAVORA_DB_NAME') !== 'savora_test') { fwrite(STDERR, "BLOCKED: admin order integration tests require savora_test\n"); exit(2); }
require_once __DIR__ . '/../lib/services/admin_order_service.php'; require_once __DIR__ . '/support/test_database.php';
function admin_order_expect(bool $ok, string $message): void { if (!$ok) throw new RuntimeException($message); }
$conn = null; $prefix = 'task18-order-' . bin2hex(random_bytes(5)); $ids = [];
try {
    $conn = savora_test_database();
    $ids['admin'] = (int) $conn->query("SELECT id FROM users WHERE role='admin' LIMIT 1")->fetch_assoc()['id']; $ids['customer'] = (int) $conn->query("SELECT id FROM users WHERE role='customer' LIMIT 1")->fetch_assoc()['id']; $ids['restaurant'] = (int) $conn->query('SELECT id FROM restaurants LIMIT 1')->fetch_assoc()['id'];
    $drivers = $conn->query("SELECT u.id FROM users u JOIN driver_profiles dp ON dp.user_id=u.id WHERE u.role='driver' AND u.status='active' AND dp.eligibility_status='eligible' AND NOT EXISTS (SELECT 1 FROM deliveries busy WHERE busy.driver_user_id=u.id AND busy.status IN ('assigned','arrived','picked_up') AND busy.superseded_at IS NULL) ORDER BY u.id LIMIT 2")->fetch_all(MYSQLI_ASSOC); admin_order_expect(count($drivers) >= 2, 'Two eligible and available Drivers are required.'); $driverA = (int) $drivers[0]['id']; $driverB = (int) $drivers[1]['id'];
    $insert = $conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,total,delivery_address) VALUES(? ,?,?, 'ready_for_pickup','card',20,20,'Task18 address')"); $reference = strtoupper($prefix . '-CANCEL'); $insert->bind_param('sii', $reference, $ids['customer'], $ids['restaurant']); $insert->execute(); $cancelId = (int) $insert->insert_id; $insert->close(); $dispatch = $conn->prepare("INSERT INTO delivery_dispatches(order_id,status,attempt_count) VALUES(?,'searching_driver',0)"); $dispatch->bind_param('i', $cancelId); $dispatch->execute(); $dispatchId = (int) $dispatch->insert_id; $dispatch->close();
    $cancel = admin_cancel_order($conn, $ids['admin'], $cancelId, 'Task18 cancellation', 1, $prefix . '-cancel'); admin_order_expect(($cancel['ok'] ?? false) === true, 'Cancellation should succeed.'); $state = $conn->query("SELECT o.status,dd.status AS dispatch_status FROM orders o JOIN delivery_dispatches dd ON dd.order_id=o.id WHERE o.id={$cancelId}")->fetch_assoc(); admin_order_expect($state['status'] === 'cancelled' && $state['dispatch_status'] === 'cancelled', 'Cancellation must close order and dispatch.');
    foreach ([['seapay', 'paid'], ['cash', 'paid']] as $index => [$method, $paymentStatus]) {
        $reference = strtoupper($prefix . '-COMPLETED-' . $index);
        $insert = $conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,total,delivery_address,version) VALUES(?,?,?,'completed',?,20,20,'Task18 address',7)");
        $insert->bind_param('siis', $reference, $ids['customer'], $ids['restaurant'], $method); $insert->execute(); $completedId = (int) $insert->insert_id; $insert->close();
        $payment = $conn->prepare('INSERT INTO payments(order_id,method,amount,status,version) VALUES(?,?,20,?,2)');
        $payment->bind_param('iss', $completedId, $method, $paymentStatus); $payment->execute(); $payment->close();
        $blocked = admin_cancel_order($conn, $ids['admin'], $completedId, 'Must remain final', 7, $prefix . '-completed-' . $index);
        $completedState = $conn->query("SELECT o.status AS order_status,o.version AS order_version,p.status AS payment_status,p.version AS payment_version FROM orders o JOIN payments p ON p.order_id=o.id WHERE o.id={$completedId}")->fetch_assoc();
        admin_order_expect(($blocked['status'] ?? 0) === 409, 'Admin cancellation must reject completed ' . $method . ' orders.');
        admin_order_expect(($completedState['order_status'] ?? '') === 'completed' && (int) ($completedState['order_version'] ?? 0) === 7 && ($completedState['payment_status'] ?? '') === 'paid' && (int) ($completedState['payment_version'] ?? 0) === 2, 'Rejected completed cancellation must not change the order or payment.');
    }
    $reference = strtoupper($prefix . '-REASSIGN'); $insert = $conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,total,delivery_address) VALUES(? ,?,?, 'assigned','cash',20,20,'Task18 address')"); $insert->bind_param('sii', $reference, $ids['customer'], $ids['restaurant']); $insert->execute(); $orderId = (int) $insert->insert_id; $insert->close(); $dispatch = $conn->prepare("INSERT INTO delivery_dispatches(order_id,status,assigned_driver_user_id,attempt_count) VALUES(?,'assigned',?,1)"); $dispatch->bind_param('ii', $orderId, $driverA); $dispatch->execute(); $dispatch->close(); $delivery = $conn->prepare("INSERT INTO deliveries(order_id,driver_user_id,status,accepted_at) VALUES(?,?, 'assigned', NOW())"); $delivery->bind_param('ii', $orderId, $driverA); $delivery->execute(); $delivery->close();
    $reassign = admin_reassign_driver($conn, $ids['admin'], $orderId, $driverB, 'Task18 reassignment', 1, $prefix . '-reassign'); admin_order_expect(($reassign['ok'] ?? false) === true, 'Reassignment should succeed: ' . json_encode($reassign)); $rows = $conn->query("SELECT driver_user_id,status,superseded_at FROM deliveries WHERE order_id={$orderId} ORDER BY id")->fetch_all(MYSQLI_ASSOC); admin_order_expect(count($rows) === 2 && (int) $rows[0]['driver_user_id'] === $driverA && $rows[0]['status'] === 'superseded' && (int) $rows[1]['driver_user_id'] === $driverB && $rows[1]['status'] === 'assigned', 'Reassignment must retain a superseded history and one active delivery.');
    echo "PASS: atomic Admin cancellation, completed terminal guards, and reassignment hold\n";
} catch (Throwable $exception) { fwrite(STDERR, $exception->getMessage() . "\n"); exit(1); }
finally { if ($conn instanceof mysqli) { foreach (['DELETE FROM delivery_milestones WHERE delivery_id IN (SELECT id FROM deliveries WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?))','DELETE FROM delivery_evidence WHERE delivery_id IN (SELECT id FROM deliveries WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?))','DELETE FROM deliveries WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?)','DELETE FROM delivery_offers WHERE dispatch_id IN (SELECT id FROM delivery_dispatches WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?))','DELETE FROM delivery_dispatches WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?)','DELETE FROM order_status_history WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?)','DELETE FROM payments WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?)','DELETE FROM orders WHERE reference_code LIKE ?'] as $sql){$stmt=$conn->prepare($sql);$pattern=$prefix.'%';$stmt->bind_param('s',$pattern);$stmt->execute();$stmt->close();} $conn->close(); } }
