<?php
declare(strict_types=1);putenv('SAVORA_DB_NAME='.(getenv('SAVORA_DB_NAME')?:'savora_test'));require_once __DIR__.'/../db.php';require_once __DIR__.'/../lib/admin_security.php';require_once __DIR__.'/../lib/admin_actions.php';
function ensure(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$actor=(int)$conn->query("SELECT id FROM users WHERE role='admin' LIMIT 1")->fetch_assoc()['id'];$customer=(int)$conn->query("SELECT id FROM users WHERE role='customer' LIMIT 1")->fetch_assoc()['id'];$restaurant=(int)$conn->query("SELECT id FROM restaurants LIMIT 1")->fetch_assoc()['id'];
$conn->query("DELETE FROM orders WHERE reference_code IN ('OPS-CANCEL-TEST','OPS-REFUND-TEST')");
$stmt=$conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,total) VALUES('OPS-CANCEL-TEST',?,?,'preparing','card',20,20)");$stmt->bind_param('ii',$customer,$restaurant);$stmt->execute();$cancelId=$stmt->insert_id;$stmt->close();$key='ops-cancel-'.bin2hex(random_bytes(5));$cancel=admin_execute_action($conn,'cancel_order',['order_id'=>$cancelId,'reason'=>'Automated cancellation safeguard test'],$actor,$key);$retry=admin_execute_action($conn,'cancel_order',['order_id'=>$cancelId,'reason'=>'Automated cancellation safeguard test'],$actor,$key);ensure(($cancel['ok']??false)&&$cancel===$retry,'Cancellation must be transactional and idempotent.');
$stmt=$conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,total) VALUES('OPS-REFUND-TEST',?,?,'delivered','card',50,50)");$stmt->bind_param('ii',$customer,$restaurant);$stmt->execute();$orderId=$stmt->insert_id;$stmt->close();$conn->query("INSERT INTO payments(order_id,method,amount,status,paid_at) VALUES({$orderId},'card',50,'paid',NOW())");$caseRef='CASE-OPS-'.bin2hex(random_bytes(3));$stmt=$conn->prepare("INSERT INTO support_cases(reference_code,order_id,case_type,reporting_role,reporting_user_id,priority,status,subject) VALUES(?,?,'refund_request','customer',?,'medium','open','Integration refund')");$stmt->bind_param('sii',$caseRef,$orderId,$customer);$stmt->execute();$caseId=$stmt->insert_id;$stmt->close();
$partial=admin_execute_action($conn,'issue_refund',['case_id'=>$caseId,'amount'=>10,'destination'=>'original_payment','reason'=>'Verified partial refund'], $actor,'ops-refund-'.bin2hex(random_bytes(5)));ensure(($partial['ok']??false),'Partial refund must succeed.');$status=$conn->query("SELECT status FROM orders WHERE id={$orderId}")->fetch_assoc()['status'];ensure($status==='delivered','Partial refund must preserve fulfillment status.');$excess=admin_execute_action($conn,'issue_refund',['case_id'=>$caseId,'amount'=>60,'reason'=>'Invalid excess'], $actor,'ops-excess-'.bin2hex(random_bytes(5)));ensure(($excess['ok']??true)===false,'Refund above remaining paid amount must fail.');
echo "PASS: order cancellation and refund operations preserve integrity and idempotency\n";
