'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');

test('dispatch API is an authenticated server-authoritative command boundary', () => {
  const api = read('api/dispatch.php');
  const demoRoute = read('lib/services/demo_route_service.php');
  assert.match(api, /savora_request_actor\(\$conn, \['driver', 'admin'\]\)/);
  assert.match(api, /savora_require_csrf/);
  assert.match(api, /savora_require_idempotency_key/);
  assert.match(api, /driver_set_availability/);
  assert.match(api, /dispatch_accept_offer/);
  assert.match(api, /dispatch_decline_offer/);
  assert.match(api, /dispatch_expire_offers/);
  assert.match(api, /'demo_start_delivery'/);
  assert.match(api, /'demo_start_shift'/);
  const lockIndex = api.indexOf('savora_idempotency_lock');
  const commandMatchIndex = api.indexOf('match ($command)');
  const demoDeliveryIndex = api.indexOf("'demo_start_delivery'");
  const demoShiftIndex = api.indexOf("'demo_start_shift'");
  assert.ok(lockIndex >= 0 && lockIndex < commandMatchIndex, 'The API lock must be acquired before command matching.');
  assert.ok(commandMatchIndex < demoDeliveryIndex && commandMatchIndex < demoShiftIndex, 'Demo commands must execute inside the locked command match.');
  assert.doesNotMatch(demoRoute, /savora_idempotency_lock/);
  assert.doesNotMatch(api, /localStorage|SavoraState|customerState/);
});
test('dispatch service exposes exclusive offer lifecycle and safe offer fields', () => {
  const service = read('lib/services/dispatch_service.php');
  const repo = read('lib/repositories/dispatch_repository.php');
  assert.match(service, /function driver_set_availability/);
  assert.match(service, /function dispatch_offer_next_driver/);
  assert.match(service, /function dispatch_accept_offer/);
  assert.match(service, /function dispatch_decline_offer/);
  assert.match(service, /function dispatch_expire_offers/);
  assert.match(service, /FOR UPDATE/);
  assert.match(service, /notification_queue/);
  assert.match(service, /audit_append/);
  assert.match(service, /savora_idempotency_find/);
  assert.match(repo, /delivery_offers/);
  assert.match(repo, /driver_locations/);
  assert.match(repo, /distance/);
  assert.doesNotMatch(service, /password|password_hash|customer_phone/);
});

test('proof of delivery is uploaded as verified multipart bytes before completion', () => {
  const upload = read('api/delivery_evidence.php');
  const dispatch = read('api/dispatch.php');
  const controller = read('js/driver_delivery.js');
  assert.match(upload, /savora_request_actor\(\$conn, \['driver'\]\)/);
  assert.match(upload, /savora_require_csrf/);
  assert.match(upload, /savora_require_idempotency_key/);
  assert.match(upload, /\$_FILES\['evidence'\]/);
  assert.match(upload, /delivery_store_evidence_upload/);
  assert.match(upload, /finally\s*\{[\s\S]*savora_idempotency_unlock[\s\S]*\}\s*if \(\$httpError !== null\) savora_error/);
  assert.match(dispatch, /evidenceIds/);
  assert.doesNotMatch(dispatch, /storedPath|mimeType|sha256|sizeBytes/);
  assert.match(controller, /FormData/);
  assert.match(controller, /api\/delivery_evidence\.php/);
  assert.match(controller, /evidenceIds/);
  assert.match(controller, /proofRequired\s*===\s*true/);
  assert.match(read('lib/repositories/order_repository.php'), /proofRequired/);
});
