<?php
declare(strict_types=1);
if (getenv('SAVORA_ENV') !== 'test' || getenv('SAVORA_DB_NAME') !== 'savora_test') { fwrite(STDERR, "BLOCKED: finance integration tests require savora_test\n"); exit(2); }
require_once __DIR__ . '/../lib/services/finance_service.php'; require_once __DIR__ . '/support/test_database.php';
function finance_expect(bool $ok, string $message): void { if (!$ok) throw new RuntimeException($message); }
$conn = null; $prefix = 'task19-finance-' . bin2hex(random_bytes(5)); $ids = [];
try {
    $conn = savora_test_database(); $ids['admin'] = (int) $conn->query("SELECT id FROM users WHERE role='admin' LIMIT 1")->fetch_assoc()['id']; $ids['customer'] = (int) $conn->query("SELECT id FROM users WHERE role='customer' LIMIT 1")->fetch_assoc()['id']; $ids['restaurant'] = (int) $conn->query('SELECT id FROM restaurants LIMIT 1')->fetch_assoc()['id'];
    $insert = $conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,total) VALUES(?,?,?,'delivered','card',50,50)"); $ref = strtoupper($prefix); $insert->bind_param('sii', $ref, $ids['customer'], $ids['restaurant']); $insert->execute(); $orderId = (int) $insert->insert_id; $insert->close(); $payment = $conn->prepare("INSERT INTO payments(order_id,method,amount,status,paid_at) VALUES(?,'card',50,'paid',NOW())"); $payment->bind_param('i', $orderId); $payment->execute(); $payment->close(); $case = $conn->prepare("INSERT INTO support_cases(reference_code,order_id,case_type,reporting_role,reporting_user_id,priority,status,subject) VALUES(?,?,'refund_request','customer',?,'medium','open','Task19 refund')"); $caseRef = 'CASE-' . strtoupper(bin2hex(random_bytes(4))); $case->bind_param('sii', $caseRef, $orderId, $ids['customer']); $case->execute(); $caseId = (int) $case->insert_id; $case->close();
    $partial = finance_issue_refund($conn, $ids['admin'], $caseId, 10.00, 'original_payment', 'Task19 partial refund', 1, $prefix . '-refund'); finance_expect(($partial['ok'] ?? false) === true, 'Partial refund should succeed.'); $excess = finance_issue_refund($conn, $ids['admin'], $caseId, 50.01, 'original_payment', 'Too much', 2, $prefix . '-excess'); finance_expect(($excess['ok'] ?? true) === false, 'Refund above remaining amount must fail.');
    echo "PASS: append-only refund and money invariants hold\n";
} catch (Throwable $exception) { fwrite(STDERR, $exception->getMessage() . "\n"); exit(1); }
finally { if ($conn instanceof mysqli) { $pattern = $prefix . '%'; foreach (['DELETE FROM ledger_entries WHERE reference_code LIKE ?','DELETE FROM refunds WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?)','DELETE FROM case_messages WHERE case_id IN (SELECT id FROM support_cases WHERE reference_code LIKE ?)','DELETE FROM support_cases WHERE reference_code LIKE ?','DELETE FROM payments WHERE order_id IN (SELECT id FROM orders WHERE reference_code LIKE ?)','DELETE FROM orders WHERE reference_code LIKE ?'] as $sql) { $stmt=$conn->prepare($sql); $stmt->bind_param('s',$pattern); $stmt->execute(); $stmt->close(); } $conn->close(); } }
