<?php
declare(strict_types=1);
require_once __DIR__.'/../db.php';require_once __DIR__.'/../lib/admin_security.php';
header('Content-Type: application/json; charset=utf-8');
if(session_status()===PHP_SESSION_NONE)session_start();
if(!isset($_SESSION['user_id'],$_SESSION['role'])){http_response_code(401);echo json_encode(['ok'=>false,'message'=>'Authentication required.']);exit;}
$userId=(int)$_SESSION['user_id'];$role=(string)$_SESSION['role'];
function platform_json(array $value,int $status=200):never{http_response_code($status);echo json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function platform_rows(mysqli $conn,string $sql,int $id):array{$stmt=$conn->prepare($sql);$stmt->bind_param('i',$id);$stmt->execute();$rows=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);$stmt->close();return $rows;}
if(($_SERVER['REQUEST_METHOD']??'GET')==='GET'){
    if($role==='customer')$orders=platform_rows($conn,"SELECT o.*,r.name restaurant_name FROM orders o JOIN restaurants r ON r.id=o.restaurant_id WHERE o.customer_user_id=? ORDER BY o.placed_at DESC",$userId);
    elseif($role==='restaurant')$orders=platform_rows($conn,"SELECT o.*,u.full_name customer_name FROM orders o JOIN restaurants r ON r.id=o.restaurant_id JOIN users u ON u.id=o.customer_user_id WHERE r.owner_user_id=? ORDER BY o.placed_at DESC",$userId);
    elseif($role==='driver')$orders=platform_rows($conn,"SELECT o.*,r.name restaurant_name,u.full_name customer_name,v.status delivery_status FROM deliveries v JOIN orders o ON o.id=v.order_id JOIN restaurants r ON r.id=o.restaurant_id JOIN users u ON u.id=o.customer_user_id WHERE v.driver_user_id=? ORDER BY o.placed_at DESC",$userId);
    else $orders=[];
    platform_json(['ok'=>true,'csrfToken'=>admin_csrf_token(),'role'=>$role,'orders'=>$orders,'serverTime'=>date(DATE_ATOM)]);
}
if(!admin_verify_csrf((string)($_SERVER['HTTP_X_CSRF_TOKEN']??'')))platform_json(['ok'=>false,'message'=>'Secure session expired.'],403);
$key=mb_substr(trim((string)($_SERVER['HTTP_IDEMPOTENCY_KEY']??'')),0,100);if($key==='')platform_json(['ok'=>false,'message'=>'Idempotency key required.'],422);
$body=json_decode((string)file_get_contents('php://input'),true);if(!is_array($body))platform_json(['ok'=>false,'message'=>'Invalid JSON.'],400);$command=(string)($body['command']??'');$payload=is_array($body['payload']??null)?$body['payload']:[];
$lookup=$conn->prepare('SELECT response_json FROM idempotency_keys WHERE actor_user_id=? AND idempotency_key=?');$lookup->bind_param('is',$userId,$key);$lookup->execute();$stored=$lookup->get_result()->fetch_assoc();$lookup->close();if($stored)platform_json(json_decode((string)$stored['response_json'],true));
$conn->begin_transaction();
try{
    $result=[];
    if($command==='place_order'&&$role==='customer'){
        $reference=mb_substr((string)($payload['id']??''),0,40);$address=mb_substr(trim((string)($payload['address']??'')),0,500);$items=is_array($payload['items']??null)?$payload['items']:[];$subtotal=round((float)($payload['subtotal']??0),2);$delivery=round((float)($payload['deliveryFee']??0),2);$total=round((float)($payload['total']??0),2);$payment=in_array(($payload['paymentMethod']??''),['wallet','cash','card'],true)?$payload['paymentMethod']:'cash';if($reference===''||$address===''||!$items||$total<=0||abs(($subtotal+$delivery)-$total)>.01)throw new RuntimeException('Order totals, address or items are invalid.');$restaurant=$conn->query("SELECT id FROM restaurants WHERE status='active' AND accepting_orders=1 ORDER BY id LIMIT 1 FOR UPDATE")->fetch_assoc();if(!$restaurant)throw new RuntimeException('No Restaurant is accepting orders.');$restaurantId=(int)$restaurant['id'];$insert=$conn->prepare("INSERT INTO orders(reference_code,customer_user_id,restaurant_id,status,payment_method,subtotal,delivery_fee,total,delivery_address,delivery_note) VALUES(?,?,?,'pending',?,?,?,?,?,?)");$note=mb_substr((string)($payload['deliveryNote']??''),0,300);$insert->bind_param('siisdddss',$reference,$userId,$restaurantId,$payment,$subtotal,$delivery,$total,$address,$note);$insert->execute();$orderId=$insert->insert_id;$insert->close();$itemStmt=$conn->prepare('INSERT INTO order_items(order_id,item_name,quantity,unit_price,options_text) VALUES(?,?,?,?,?)');foreach($items as $item){$name=mb_substr((string)($item['name']??'Item'),0,160);$quantity=max(1,min(99,(int)($item['quantity']??1)));$price=max(0,(float)($item['unitPrice']??0));$options=mb_substr(json_encode($item['options']??[],JSON_UNESCAPED_UNICODE),0,500);$itemStmt->bind_param('isids',$orderId,$name,$quantity,$price,$options);$itemStmt->execute();}$itemStmt->close();$history=$conn->prepare("INSERT INTO order_status_history(order_id,status,actor_role,actor_user_id) VALUES(?,'pending','customer',?)");$history->bind_param('ii',$orderId,$userId);$history->execute();$history->close();$paymentStmt=$conn->prepare("INSERT INTO payments(order_id,method,amount,status,paid_at) VALUES(?,?,?,'paid',NOW())");$paymentStmt->bind_param('isd',$orderId,$payment,$total);$paymentStmt->execute();$paymentStmt->close();$result=['orderId'=>$orderId,'referenceCode'=>$reference,'status'=>'pending'];
    }elseif($command==='restaurant_order_status'&&$role==='restaurant'){
        $reference=mb_substr((string)($payload['reference_code']??''),0,40);$target=(string)($payload['status']??'');$map=['confirmed'=>'accepted','preparing'=>'preparing','ready_for_pickup'=>'ready_for_pickup','cancelled'=>'cancelled'];$target=$map[$target]??'';$stmt=$conn->prepare('SELECT o.id,o.status,o.version FROM orders o JOIN restaurants r ON r.id=o.restaurant_id WHERE o.reference_code=? AND r.owner_user_id=? FOR UPDATE');$stmt->bind_param('si',$reference,$userId);$stmt->execute();$order=$stmt->get_result()->fetch_assoc();$stmt->close();$allowed=['pending'=>['accepted','cancelled'],'accepted'=>['preparing','cancelled'],'preparing'=>['ready_for_pickup']];if(!$order||!in_array($target,$allowed[$order['status']]??[],true))throw new RuntimeException('Restaurant transition is not allowed.');$update=$conn->prepare('UPDATE orders SET status=?,version=version+1 WHERE id=?');$update->bind_param('si',$target,$order['id']);$update->execute();$update->close();$history=$conn->prepare("INSERT INTO order_status_history(order_id,status,actor_role,actor_user_id) VALUES(?,?,'restaurant',?)");$history->bind_param('isi',$order['id'],$target,$userId);$history->execute();$history->close();$result=['referenceCode'=>$reference,'status'=>$target];
    }elseif($command==='driver_milestone'&&$role==='driver'){
        $reference=mb_substr((string)($payload['reference_code']??''),0,40);$milestone=(string)($payload['milestone']??'');$map=['arrived'=>'assigned','picked_up'=>'picked_up','delivered'=>'delivered'];if(!isset($map[$milestone]))throw new RuntimeException('Driver milestone is invalid.');$stmt=$conn->prepare('SELECT v.id delivery_id,o.id order_id,o.status FROM deliveries v JOIN orders o ON o.id=v.order_id WHERE o.reference_code=? AND v.driver_user_id=? FOR UPDATE');$stmt->bind_param('si',$reference,$userId);$stmt->execute();$deliveryRow=$stmt->get_result()->fetch_assoc();$stmt->close();if(!$deliveryRow)throw new RuntimeException('Assigned delivery not found.');$deliveryStatus=$milestone;$orderStatus=$map[$milestone];$update=$conn->prepare('UPDATE deliveries SET status=?,delivered_at=IF(?="delivered",NOW(),delivered_at),version=version+1 WHERE id=?');$update->bind_param('ssi',$deliveryStatus,$deliveryStatus,$deliveryRow['delivery_id']);$update->execute();$update->close();$orderUpdate=$conn->prepare('UPDATE orders SET status=?,version=version+1 WHERE id=?');$orderUpdate->bind_param('si',$orderStatus,$deliveryRow['order_id']);$orderUpdate->execute();$orderUpdate->close();$event=$conn->prepare('INSERT INTO delivery_milestones(delivery_id,status,actor_user_id) VALUES(?,?,?)');$event->bind_param('isi',$deliveryRow['delivery_id'],$milestone,$userId);$event->execute();$event->close();$result=['referenceCode'=>$reference,'status'=>$milestone];
    }else throw new RuntimeException('Command is not allowed for this role.');
    $response=['ok'=>true,'message'=>'Platform state synchronized.','data'=>$result];$json=json_encode($response,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$store=$conn->prepare('INSERT INTO idempotency_keys(actor_user_id,idempotency_key,action,response_json) VALUES(?,?,?,?)');$store->bind_param('isss',$userId,$key,$command,$json);$store->execute();$store->close();$conn->commit();platform_json($response);
}catch(Throwable $error){$conn->rollback();platform_json(['ok'=>false,'message'=>$error->getMessage()],422);}
